server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      bootstrap-servers: localhost:9092
      application-id: ${spring.application.name}
      client-id: ${spring.application.name}-stream
#      properties:
#        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#        default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
#        default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndFailExceptionHandler
    properties:
      schema.registry.url: http://localhost:8081
      bootstrap.servers: ${spring.kafka.bootstrap-servers}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: my-group

#spring:
#  kafka:
#    consumer:
#      bootstrap-servers:
#        - localhost:9092
#      group-id: my-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
#    bootstrap-servers: localhost:9092
##    producer:
##      bootstrap-servers:
##        - localhost:9092
##      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
##      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
##
##